### ISSUE TITLE
Can't return zathura to default

### ISSUE THREAD

**Issue by breadmvn** [Everblush/zathura#1]
I recently switched to linux and I was looking for something to make my zathura look good but when I wanted to return to defualt by uninstalling and reinstalling it didn't go back to normal.
Please help

**Comment by mngshm** [comment]
Can you please explain your issue more with a screenshot ?

**Comment by breadmvn** [comment]
![image](https://user-images.githubusercontent.com/105238863/180603482-e29468c0-a2a8-4299-a083-538e7c63a7b7.png)

**Comment by breadmvn** [comment]
it inverts images and I and i want to return it to default

**Comment by mngshm** [comment]
We'll because of the config images also change we are not able to do anything on it. If I'll find some fix I'll surely push to the repo :(

**Comment by breadmvn** [comment]
ok , is it possible to like "unclone" out of the repo?

**Comment by mngshm** [comment]
do you want to switch to your default zathura config ? 
if you want to do so just 
```rm -rf ~/.config/zathura/zathurarc``` and now you're set back to default.

**Comment by breadmvn** [comment]
sorry forgot to close the issue
